name: CI-CD to Cloud Run

on:
  push:
    branches: [main]

env:
  GAR_HOST: us-central1-docker.pkg.dev
  GAR_REPO: emotionarc-api/api-repo
  IMAGE_NAME: mini-api
  REGION: us-central1
  SERVICE: emotionarc-api

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up gcloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure gcloud
      run: gcloud config set project emotionarc-api

    - name: Build & push container
      run: |
        TAG=$(echo $GITHUB_SHA | cut -c1-7)
        docker build -t ${IMAGE_NAME}:${TAG} .
        docker tag  ${IMAGE_NAME}:${TAG}  ${GAR_HOST}/${GAR_REPO}/${IMAGE_NAME}:${TAG}
        docker push ${GAR_HOST}/${GAR_REPO}/${IMAGE_NAME}:${TAG}

    - name: Deploy to Cloud Run
      run: |
        TAG=$(echo $GITHUB_SHA | cut -c1-7)
        gcloud run deploy ${SERVICE} \
          --image ${GAR_HOST}/${GAR_REPO}/${IMAGE_NAME}:${TAG} \
          --region ${REGION} --platform managed --allow-unauthenticated
